### ISSUE TITLE
If code ends with comment, error is returned

### ISSUE THREAD

**Issue by jnccloud** [ImXirvin/xv-dev#6]
If Lua ends with a comment sans a new line, it will throw an exception.

Comment without new line:
![image](https://user-images.githubusercontent.com/58707473/209042524-68af2781-1c9d-4d17-8a1e-0952dcb9a9ba.png)

With new line:
![image](https://user-images.githubusercontent.com/58707473/209042544-68d01177-a8be-494c-8ed6-0fe0f5068fe7.png)

**Comment by ImXirvin** [comment]
Ahh I see, its because it  comments out the `end` from `(function end)()`.

**Comment by ImXirvin** [comment]
Fixed
